CoreDemo/Controllers/UserLayoutController.cs
using System;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Threading;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace CoreDemo.Controllers
{
    [AllowAnonymous]
    public class UserLayoutController : Controller
    {
        public PartialViewResult FooterPartialView()
        {
            return PartialView();
        }

        public PartialViewResult NavbarPartialView()
        {
            return PartialView();
        }

        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            ViewData["culture"] = culture;

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo(culture);
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo(culture);

            return LocalRedirect(returnUrl); 
        }

    }
}

CoreDemo/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/x-icon" href="~/favicon.ico">

    <title>@ViewData["Title"] | ASP.NET Core MVC</title>

    <link href="~/adminTemplate/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/adminTemplate/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/adminTemplate/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="~/adminTemplate/css/animate.css" rel="stylesheet">
    <link href="~/adminTemplate/css/style.css" rel="stylesheet">
    <link href="~/adminTemplate/css/plugins/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/adminTemplate/css/popup.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/writerTemplate/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link href="~/css/site.css" rel='stylesheet' type='text/css' />

</head>

<body>

    <div id="wrapper">

        @await Component.InvokeAsync("AdminSidebar")

        <div id="page-wrapper" class="gray-bg">

            @await Component.InvokeAsync("AdminNavbar")

            @RenderBody()

        </div>
    </div>



    <!-- Mainly scripts -->
    <script src="~/adminTemplate/js/jquery-3.1.1.min.js"></script>
    <script src="~/adminTemplate/js/popper.min.js"></script>
    <script src="~/adminTemplate/js/bootstrap.js"></script>
    <script src="~/adminTemplate/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/adminTemplate/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Peity -->
    <script src="~/adminTemplate/js/plugins/peity/jquery.peity.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/adminTemplate/js/inspinia.js"></script>

    <!-- iCheck -->
    <script src="~/adminTemplate/js/plugins/iCheck/icheck.min.js"></script>

    <!-- Peity -->
    <script src="~/adminTemplate/js/demo/peity-demo.js"></script>

    <!-- Sweet Alert -->
    <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>

    <!-- Toastr -->
    <script src="~/adminTemplate/js/plugins/toastr/toastr.min.js"></script>

    <!-- CkEditor -->
    <script src="~/ckeditor/ckeditor.js"></script>

    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green'
            });
        });
    </script>

    <script>

        window.onload = function () {
        @Html.Raw(TempData["Message"])
                }

    </script>

    @await RenderSectionAsync("scripts" , required: false)
</body>

</html>

CoreDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CoreDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand">CoreDemo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark">Anasayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark">Sekme 2</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark">Yardım</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - CoreDemo - <a>Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoreDemo/Views/Shared/_UserLayout.cshtml
@inject IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> LocOptions

@{
    Layout = null;

    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";

    var culture = Context.Features.Get<IRequestCultureFeature>();
    var cultureList = LocOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = x.Name }).ToList();
}

<!DOCTYPE html>
<html>

<head>
    <title>@ViewData["Title"] | ASP.NET Core MVC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="~/weblogTemplate/web/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/weblogTemplate/web/css/single.css" rel="stylesheet" type="text/css">
    <link href="~/weblogTemplate/web/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/lib/toastr/toastr.min.css" rel='stylesheet' type='text/css' />
    <link href="~/weblogTemplate/web/css/fontawesome-all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
    <link href="~/css/site.css" rel='stylesheet' type='text/css' />
</head>

<body>
    <!--Header-->



    <header>
        <div class="top-bar_sub_w3layouts container-fluid">
            <div class="row">
                <div class="col-md-4 logo text-left">
                    <a class="navbar-brand" href="/Blog/GetAll">
                        <i class="fab fa-linode"></i> 
                    </a>
                </div>

                @await Component.InvokeAsync(nameof(CoreDemo.ViewComponents.LoginRegisterNavbarViewComponent).Replace("ViewComponent",""))

                <!-- social media -->
                <div class="col-md-4 log-icons text-right">
                    
                    <form asp-action="SetLanguage" asp-controller="UserLayout" method="post" 
                          asp-route-returnUrl="@returnUrl">
                        <select name="culture" 
                                asp-for="@culture.RequestCulture.UICulture.Name"
                                asp-items="cultureList"
                                onchange="this.form.submit();">

                        </select>
                    </form>

                </div>
                <!-- //social media -->

            </div>
        </div>

        <div class="header_top" id="home">

            @await Html.PartialAsync($"../{nameof(CoreDemo.Controllers.UserLayoutController).Replace("Controller","")}/{nameof(CoreDemo.Controllers.UserLayoutController.NavbarPartialView)}")

        </div>
    </header>
    <!--//header-->
    <!--/main-->
    <section class="main-content-w3layouts-agileits">
        <div class="container">
            @RenderBody()
        </div>
    </section>
    <!--//main-->
    <!--footer-->
    @await Html.PartialAsync($"../{nameof(CoreDemo.Controllers.UserLayoutController).Replace("Controller","")}/{nameof(CoreDemo.Controllers.UserLayoutController.FooterPartialView)}")
    <!-- //footer -->
    <!---->
    <!-- js -->
    <script src="~/weblogTemplate/web/js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!--/ start-smoth-scrolling -->
    <script src="~/weblogTemplate/web/js/move-top.js"></script>
    <script src="~/weblogTemplate/web/js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 900);
            });
        });
    </script>
    <!--// end-smoth-scrolling -->

    <script>
        $(document).ready(function () {
            
                                    var defaults = {
                                            containerID: 'toTop', // fading element id
                                        containerHoverID: 'toTopHover', // fading element hover id
                                        scrollSpeed: 1200,
                                        easingType: 'linear'
                                        };
                                    

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#home" class="scroll" id="toTop" style="display: block;">
        <span id="toTopHover" style="opacity: 1;"> </span>
    </a>

    @RenderSection("scripts", required: false)

    <!-- //Custom-JavaScript-File-Links -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/site.js" type="text/javascript"></script>

</body>

</html>

<script>

    window.onload = function () {
    @Html.Raw(TempData["Message"])
            }

</script>

CoreDemo/Views/Shared/_WriterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] | ASP.NET Core MVC</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/writerTemplate/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/writerTemplate/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/writerTemplate/assets/css/style.css">
    <!-- Toastr -->
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel='stylesheet' type='text/css' />
    <!-- End layout styles -->

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        @await Component.InvokeAsync("WriterNavbar")
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            @await Html.PartialAsync("../Home/WriterSidebar")
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/writerTemplate/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/writerTemplate/assets/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/writerTemplate/assets/js/off-canvas.js"></script>
    <script src="~/writerTemplate/assets/js/hoverable-collapse.js"></script>
    <script src="~/writerTemplate/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/writerTemplate/assets/js/dashboard.js"></script>
    <script src="~/writerTemplate/assets/js/todolist.js"></script>
    <!-- Sweet Alert -->
    <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
    <!-- Toastr -->
    <script src="~/lib/toastr/toastr.min.js"></script>
    <!-- CkEditor -->
    <script src="~/ckeditor/ckeditor.js"></script>
    <!-- End custom js for this page -->
</body>

<script>

    window.onload = function () {
    @Html.Raw(TempData["Message"])
    }

</script>

</html>